# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy rest of the source code
COPY . .

# Build the project
RUN npm run build

# Expose any ports if required (none specified, but can be adjusted)

# Set environment variables if needed
ENV NODE_ENV=production

# Command to run the MCP server
CMD ["node", "build/index.js"]
